project:
  type: book

lang: fr

book:
  title: "L'Art ~~de la guerre~~ du Management"
  author: 
    name: "Philippe Peret"
    orcid: 0009-0003-9666-7490
    url: https://www.linkedin.com/in/philippeperet/
  date: today
  sidebar: 
    footer: "</br>[![](image/by-nc-sa.png){height=42px}](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr)"
  chapters:
    - index.qmd
    # - introduction.qmd
    - part: "1"
      chapters:
      - part-one-intro.qmd
      - conditions-meteorologiques-terrain.qmd
      - commandement.qmd
      - doctrine.qmd
      - influence-morale.qmd
      - part-one-conclusion.qmd
    - part: "2"
      chapters:
      - xxx.qmd
      - yyy.qmd
    #- conclusion.qmd
    #- references.qmd
  #appendices:
    #- xxx.qmd
  page-footer:
    border: false
    left: "Copyright 2025, Philippe Peret"
    right: 
      - icon: github
        href: https://github.com/thekangaroofactory
        target: _blank
      - icon: linkedin 
        href: https://www.linkedin.com/in/philippeperet/
        target: _blank

bibliography: references.bib

format:
  html:
    link-external-newwindow: true
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
