# Le commandement

xxx intro...

Par autorité, j’entends les qualités de sagesse, d’équité, d’humanité, de courage et de sévérité du général.
De là vient que l’armée l’appelle « Le Respecté ».

S’il n’était fait mention du grade de général, nous pourrions tout à fait reprendre ce passage à l’identique.
Néanmoins, il semble que la notion de respect puisse prêter à confusion dans le sens où, dans une organisation d’une entreprise, le respect tient pour parti de la position hiérarchique et du pouvoir qui en découle, plus que d’une légitimité acquise à l’exercice de ce pouvoir.
De même, la notion de sévérité laisserait entendre qu’un responsable doit être sévère pour être respecté alors que les organisations où le « chef » est craint sont presque toujours inefficaces et vouées à l’échec sur le long terme, en particulier car cette crainte inspirée empêche toute forme de débat, d’idée nouvelle et de créativité.

Par autorité, j’entends les qualités de sagesse, d’équité, d’humanité et de courage du manager.
De là vient qu’il est respecté au sein de l’organisation.

De manière que le respect est bien gagné par le manager par sa culture managériale, ses actions et son comportement général et non un dû lié à sa position dans la chaîne de commande de l’organisation.
