---
title: "preface"
---

Je ne sais si je suis ou si j'ai été un bon manager.

En revanche, je sais la longue litanie des managers toxiques, xxx des incompétents xxx ou/et de tous ceux qui – par absence de vision ou même simplement par incompétence – entrainent leurs équipes dans des situations où leurs membres sont frappés par la démotivation, usés de devoir absorber les consignes contradictoires et / ou xxx.

En 2019, alors que j'étais moi même confronté à une situation de harcèlement moral au travail (ou décrire la situation absence de tâche, post subalterne), je reprenais la lecture de l'Art de la Guerre xxx.
dire que j'allais travailler avec le livre tous les jours sur le coin de mon bureau ?

A ma grande surprise, je découvrai cette ouvrage sous un nouveau jour, chaque page de ce manuel de doctrine militaire résonnant de manière particulièrement judicieuse non seulement avec la situation dans laquelle je me trouvais, mais également avec nombre de mes expériences passées.

Alors que je me rendais chaque jour au travail avec ce livre, j'ai commencé à prendre des notes autour des chapitres, à commenter des passages et à sélectionner ceux qui pouvaient se transposer à la situation.

A ceux qui doutent, à ceux qui subissent, j'espère que – comme moi – vous trouverez dans ces chapitres xxx (trouver un exemple de citation où on amène l'enemi sur son propre terrain).
